name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate dependencies
        run: mvn validate

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Generate Jacoco Report
        run: mvn jacoco:report

  sonar-analysis:
    needs: unit-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=deborafaria01_spring-rest-data-security \
            -Dsonar.organization=deborafaria01 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  system-test:
    needs: [unit-test, sonar-analysis]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate dependencies
        run: mvn validate

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run System Tests
        run: mvn verify
